### ISSUE TITLE
Directone has 3 jobs on peviitor.ro and only 2 on their website for Romania

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#17]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for directone in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://www.directone.ro/careers/

**Actual Results:**
Directone has 3 jobs on peviitor.ro and 2 on their website for Romania.

**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on https://www.directone.ro/careers/

**Comment by sebiboga** [comment]
@CristianDoditoiu  I fixed Github Actions https://github.com/lorenaberchesan85/Directone/actions
please recheck

**Comment by CristianDoditoiu** [comment]
Verified. Status: Failed. It still reproduces. Now it has two jobs on their site and on peviitor we have 4 (2 of them take the user to another website, not DIRECTONE).
