### ISSUE TITLE
3pillarglobal - the Logo of the Company "3pillar global" appears for 2 times

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/firme-peviitor#73]
Environment: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search for the company "3pillarglobal"
3.Check the logo
4.Run the scrapers.peviitor.ro
5.Check the company data 
 
EXPECTED RESULTS:
The "3pillar global" Company logo appears once
Company data is displayed on the scrapers.peviitor.ro

ACTUAL RESULTS:
On the firme.peviitor.ro the logo of the  Company "3pillarglobal"  appears for 2 times and return same message
The company data isn't displayed on the scrapers.peviitor.ro, the scraper didn't return data

![image](https://github.com/peviitor-ro/firme-peviitor/assets/127322865/f809491a-26ff-475e-9d7f-d307261ea996)
![image](https://github.com/peviitor-ro/firme-peviitor/assets/127322865/77843ff9-dd85-47b0-a06d-d9880d43a253)
![image](https://github.com/peviitor-ro/firme-peviitor/assets/127322865/ff5e78c4-3fbf-4b5c-b13e-3fd781dc625e)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
**Retesting:**
Ran scraper. Checked the company data. Company data is still not displayed on scrapers.peviitor.ro. The scraper has not yet returned data

![Image](https://github.com/peviitor-ro/firme-peviitor/assets/127322865/e5fb548a-4019-4ee4-b199-561c530dad72)

**Comment by AdiVanca** [comment]
3pillar appears twice
![a47](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/e6e5d93a-254e-4490-b83b-fb38b313efca)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting the company appears only once
